### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by rscar051** [pitest/pitclipse#115] opened 2020-05-30 02:06 UTC
Connecting to: localhost/127.0.0.1:53545
Connected
Received request: PitRequest [options=PitOptions [reportDir=C:\Users\rache\eclipse-workspace\.metadata\.plugins\org.pitest.pitclipse.core\html_results, classUnderTest=dateP.DateTest, classesToMutate=[dateP.Date, dateP.DateExceptionTest, dateP.DateTest, dateP.DateUnitTest], sourceDirs=[C:\Users\rache\OneDrive\summer 2020\SEG\date\Date\src, C:\Users\rache\OneDrive\summer 2020\SEG\date\Date\tests], packages=[], threads=4, historyLocation=null, excludedClasses=[], excludedMethods=[], avoidCallsTo=[java.util.logging, org.apache.log4j, org.slf4j, org.apache.commons.logging], mutators=[DEFAULTS], timeoutConst=3000, timeoutFactor=1.25], projects=[Date]]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.pitest.reloc.xstream.core.util.Fields (file:/C:/Users/rache/.p2/pool/plugins/org.pitest.osgi_1.1.9.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of org.pitest.reloc.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:00:36 p.m. PIT >> FINE : Running report with ReportOptions [targetClasses=[^dateP\.Date$, ^dateP\.DateExceptionTest$, ^dateP\.DateTest$, ^dateP\.DateUnitTest$], excludedMethods=[], excludedClasses=[], codePaths=[], reportDir=C:\Users\rache\eclipse-workspace\.metadata\.plugins\org.pitest.pitclipse.core\html_results, historyInputLocation=null, historyOutputLocation=null, sourceDirs=[C:\Users\rache\OneDrive\summer 2020\SEG\date\Date\src, C:\Users\rache\OneDrive\summer 2020\SEG\date\Date\tests], classPathElements=[C:\Users\rache\OneDrive\summer 2020\SEG\date\Date\bin, C:\Users\rache\.p2\pool\plugins\org.junit_4.13.0.v20200204-1500.jar, C:\Users\rache\.p2\pool\plugins\org.hamcrest.core_1.3.0.v20180420-1519.jar, C:\Users\rache\.p2\pool\plugins\org.pitest.command-line-osgi_1.1.9.jar, C:\Users\rache\.p2\pool\plugins\org.pitest.html-report-osgi_1.1.9.jar, C:\Users\rache\.p2\pool\plugins\org.pitest.osgi_1.1.9.jar, C:\Users\rache\.p2\pool\plugins\org.pitest.pitrunner_1.1.6.201607050705.jar, C:\Users\rache\.p2\pool\plugins\org.pitest.guava-shade-osgi_18.0.0.jar], mutators=[DEFAULTS], dependencyAnalysisMaxDistance=-1, mutateStaticInitializers=false, jvmArgs=[], numberOfThreads=4, timeoutFactor=1.25, timeoutConstant=3000, targetTests=[^dateP\.DateTest$], loggingClasses=[java.util.logging, org.apache.log4j, org.slf4j, org.apache.commons.logging], maxMutationsPerClass=0, verbose=true, failWhenNoMutations=false, outputs=[HTML, PITCLIPSE_MUTATIONS], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], mutationUnitSize=0, shouldCreateTimestampedReports=true, detectInlinedCode=false, exportLineCoverage=false, mutationThreshold=0, coverageThreshold=0, mutationEngine=gregor, javaExecutable=null, includeLaunchClasspath=true]
10:00:36 p.m. PIT >> FINE : System class path is C:\Users\rache\OneDrive\summer 2020\SEG\date\Date\bin;C:\Users\rache\.p2\pool\plugins\org.junit_4.13.0.v20200204-1500.jar;C:\Users\rache\.p2\pool\plugins\org.hamcrest.core_1.3.0.v20180420-1519.jar;C:\Users\rache\.p2\pool\plugins\org.pitest.command-line-osgi_1.1.9.jar;C:\Users\rache\.p2\pool\plugins\org.pitest.html-report-osgi_1.1.9.jar;C:\Users\rache\.p2\pool\plugins\org.pitest.osgi_1.1.9.jar;C:\Users\rache\.p2\pool\plugins\org.pitest.pitrunner_1.1.6.201607050705.jar;C:\Users\rache\.p2\pool\plugins\org.pitest.guava-shade-osgi_18.0.0.jar
10:00:36 p.m. PIT >> FINE : Maximum available memory is 4078 mb
Closing server
Closed
Exception in thread "main" java.lang.IllegalArgumentException
	at org.pitest.reloc.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.reloc.asm.ClassReader.<init>(Unknown Source)
	at org.pitest.classinfo.ClassInfoVisitor.getClassInfo(ClassInfoVisitor.java:41)
	at org.pitest.classinfo.Repository.nameToClassInfo(Repository.java:70)
	at org.pitest.classinfo.Repository.fetchClass(Repository.java:60)
	at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:16)
	at org.pitest.classinfo.NameToClassInfo.apply(NameToClassInfo.java:6)
	at org.pitest.functional.FCollection.flatMapTo(FCollection.java:56)
	at org.pitest.functional.FCollection.flatMap(FCollection.java:66)
	at org.pitest.classpath.CodeSource.getCode(CodeSource.java:46)
	at org.pitest.mutationtest.verify.DefaultBuildVerifier.verify(DefaultBuildVerifier.java:32)
	at org.pitest.mutationtest.tooling.MutationCoverage.verifyBuildSuitableForMutationTesting(MutationCoverage.java:206)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:108)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:103)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:45)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:76)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
	at org.pitest.pitclipse.pitrunner.PitRunner.runPIT(PitRunner.java:46)
	at org.pitest.pitclipse.pitrunner.PitRunner.main(PitRunner.java:25)

**Comment by echebbi** [comment] 2020-05-30 09:31
Thanks for the report! This issue looks similar to #74; it seems from the stacktrace that you're using an old version of Pitclipse so I would suggest upgrading to the lastest (2.1.0).

If that does not solve the issue, could you please:

 - check that you have installed the latest version of Pitclipse (Pitclipse 2.1.0, which embeds Pitest 1.4.11) from _Help > About Eclipse IDE > Installation Details_
 - share the steps I can follow to reproduce the issue.

I'll need all these information to investigate the bug. Next time you can also use the [bug report template](https://github.com/pitest/pitclipse/issues/new?assignees=&labels=bug&template=bug_report.md&title=) which asks them explicitely.

**Comment by echebbi** [comment] 2020-06-23 20:03
@rscar051 any news on this? Without new inputs I'll consider this issue as a duplicate of #74 and will close it.

**Comment by LorenzoBettini** [comment] 2021-07-12 16:23
I'm closing this since that seems really related to an old version of pitclipse (and pit)

**Closed by LorenzoBettini** 2021-07-12 16:23 UTC
