### ISSUE TITLE
Must have mutations and summary window open BEFORE running tests

### ISSUE THREAD

**Issue by grahamtt** [pitest/pitclipse#63] opened 2015-11-17 17:55 UTC
If I open the `PIT mutations` or `PIT Summary` windows after running the test suite, they are blank.

**Comment by LorenzoBettini** [comment] 2021-05-06 12:34
I cannot reproduce it anymore so I'd close this.
Please feel free to reopen it in case you still have the problem

**Closed by LorenzoBettini** 2021-05-06 12:34 UTC
Labels: a: feature request :email:, for: IDE :waxing_crescent_moon:, impacts: ux :blonde_man:, is: available :checkered_flag:, priority: medium :sun_behind_large_cloud:
