### ISSUE TITLE
Is this project still developed?

### ISSUE THREAD

**Issue by LorenzoBettini** [pitest/pitclipse#76] opened 2019-06-04 08:35 UTC
I'm experiencing problems when using Java 11, as already reported in other issues. From what I understand, it should be enough to use an updated version of PIT (1.4.x).

I was trying to work on that but I cannot seem to import and develop Eclipse projects of pitclipse properly.

The last release dates back to 2016. Is this project still developed?

I see there's a fork, in particular this branch https://github.com/echebbi/pitclipse/tree/update-project-architecture from @echebbi, which seems to solve most issues.

**Comment by echebbi** [comment] 2019-06-04 10:03
Hi @LorenzoBettini, I indeed started to contribute to the project. I am also in touch with @philglover to discuss the future of the project so I hope that a new version will be released in the incoming weeks.

Currently my changes mainly consist in upgrading dependencies' version in order to improve maintenability, I will focus on bug fixing afterwards.
 
I did not test my branch against Java 11 but it uses Java 8 and PIT 1.4.6 so you can give it a try. Since it is not released yet you'll have to build it manually:
1. Clone my branch
2. `mvn clean verify`
3. Install plug-ins from the generated update site: `releng/org.pitest.pitclipse.p2/target/repository`

Since each bundle is now an Eclipse project it should be easier to make changes if needed.

**Comment by LorenzoBettini** [comment] 2019-06-05 11:37
Great news!
Please let me know if I can help somehow.

**Comment by echebbi** [comment] 2019-06-12 22:45
Thank you, any help will be greatly appreciated! 

For now we asked to transfer the repository under the Pitest organization (https://github.com/hcoles/pitest/issues/619), I believe that things will progress quickly after that.

**Comment by echebbi** [comment] 2019-08-15 10:33
Hi @LorenzoBettini, PR #80 is finally merged and comes with a lot of updates. Feel free to check open issues and to read the [contribution guide](https://github.com/pitest/pitclipse/blob/master/CONTRIBUTING.md) if you're willing to help.

Can this issue be closed?

**Comment by LorenzoBettini** [comment] 2019-09-27 09:45
Hi @echebbi but the new version hasn't been released in the update site, has it?

**Comment by echebbi** [comment] 2019-10-01 20:47
Hi,

Indeed, sorry about that: I didn't take the time to work on #79 yet. I plan do this in this incoming days though.

I was suggesting closing the issue because of the title you gave it: even if I do not have as much free time as I would, I can confirm that the project is still develop. Do you prefer keeping it open until a new Pitclipse release fixes the issues you mentioned?

**Comment by LorenzoBettini** [comment] 2019-10-02 09:30
You're right about the now misleading title, but I'd be tempted to keep it open until the new version is released :)

**Comment by echebbi** [comment] 2019-10-02 09:35
Alright then, I'll keep you updated.

**Comment by echebbi** [comment] 2019-10-04 23:14
I just deployed the new `2.0.0` release #87, you can install it from the following update site: 

- https://dl.bintray.com/kazejiyu/Pitclipse/updates/

I tested it on Mars 2 & 2019-09 with both Java 1.8 and Java 12; Pitclipse works as expected with standard Java projects. However, projects using Java 9 modules are not supported yet.

If the current release suits your needs I'll close this issue and fill a new one dedicated to support Java 9 modules.

**Comment by LorenzoBettini** [comment] 2019-10-11 12:01
Hi

I've just tried that and it works great! :)

Just one problem though: there are 3 features in this update site I thought that installing Pitclipse UI would be enough but then I get exceptions while running due to missing listeners. It looks like all of them must be installed and this is kind of confusing...

**Comment by echebbi** [comment] 2019-10-11 14:42
Hi

> I've just tried that and it works great! :)

Good news!

> I thought that installing Pitclipse UI would be enough but then I get exceptions while running due to missing listeners

The three features are indeed mandatory, however I thought I added dependencies from `Pitclipse UI` to `Pitclipse Core` to force Eclipse IDE to install the three of them, even if only `Pitclipse UI`. I will check that.

> this is kind of confusing...

I can understand that. I decided to provide three features so that users which would like to use only PIT or to run Pitclipse in an headless mode could install only one of them. 

I can think of three alternatives:

1. The update site provides the three features as long as I can ensure that of all them are installed, even if only `Pitclipse UI` is selected.
2. The update site provides a unique feature embedding all the bundles so users aren't confused.
3. The update site provides two categories: 
    - a `User` category containing a unique feature embedding all the bundles,
    - a `Developer` category containing the three existing features.

Ideally, I believe that 1) is the best fit as 2) could bother plug-in developers that'd like to use Pitclipse and 3) sounds a bit clumsy. You have more experience than me, what do you think about that?

**Comment by LorenzoBettini** [comment] 2019-10-11 15:01
Typically "Developer Resources" corresponds to source bundles (if you use Tycho, that's the name of the source features), so the two categories could be misleading.

I think the important point is that the UI feature, which is meant to be installed in Eclipse, contains the other two mandatory features.

If I understand correctly both UI and Core depends on the Pitest feature right?

Thus, the important thing is that these dependencies are respected (meaning that installing one feature also installs the dependencies):

`Pitclipse UI` -> `Pitclipse Core` -> `Pitest`

If these are respected, having the 3 features as it is now it's OK.

**Comment by LorenzoBettini** [comment] 2019-10-11 15:05
From what I see here https://github.com/pitest/pitclipse/blob/master/features/org.pitest.pitclipse.ui.feature/feature.xml the UI feature does NOT include the Core feature, and the Core feature https://github.com/pitest/pitclipse/blob/master/features/org.pitest.pitclipse.core.feature/feature.xml does not include the Pitest feature, that's the problem.

In general, your features should "include" other features of yours, and "requires" stuff from other projects. I also suggest NOT to "require" single plugins but features.

Can I help you with that?

**Comment by echebbi** [comment] 2019-10-11 17:40
> In general, your features should "include" other features of yours, and "requires" stuff from other projects. I also suggest NOT to "require" single plugins but features.

Thanks for the explanations!

> Can I help you with that?

Thank you, I am a bit busy at the moment but I believe that I should be able to handle the issue by Monday. May I ask you to review the changes once I'm done to make sure I declared dependencies properly? Alternatively, any PR will be gladly accepted if you want to contribute.

**Closed** 2020-02-06 09:22 UTC
